app_index:
    path: /
    defaults: { _controller: APICoreBundle:Core:index }

api_login_check:
    path: /login_check
    
api_carto:
    resource: "@APICartoBundle/Resources/config/routing.yml"
    prefix:   /carto

api_metadata:
    resource: "@APIMetadataBundle/Resources/config/routing.yml"
    prefix:   /metadata/

api_biblio:
    resource: "@APIBiblioBundle/Resources/config/routing.yml"
    type: rest
    prefix:   /biblio/

api_import:
    resource: "@APIImportBundle/Resources/config/routing.yml"
    type: rest
    prefix:   /import/

api_magic_taxref:
    resource: "@APIMagicTaxrefBundle/Resources/config/routing.yml"
    type: rest
    prefix:   /magic-taxref/

api_projet:
    resource: "@APIProjetBundle/Resources/config/routing.yml"
    type: rest
    prefix:   /etude/