visu_security_login:
    path:     /login
    defaults: { _controller: VisuConsultationBundle:Security:login }

ofsa_security_logout:
    path:     /deconnexion
    defaults: { _controller: VisuConsultationBundle:Security:logout }

visu_consultation_carte:
    path:     /
    defaults: { _controller: VisuConsultationBundle:Cartographie:carte }

visu_carto_repartition_geojson:
    path:     /indicateur/repartition.geojson
    defaults: { _controller: VisuConsultationBundle:Cartographie:repartition }
    options:
        expose: true

visu_carto_pc_geojson:
    path:     /indicateur/pc.geojson
    defaults: { _controller: VisuConsultationBundle:Cartographie:geoJsonPC }
    options:
        expose: true

visu_carto_pc_infobulle:
    path:     /information/pc/{echelle}/{maille_id}
    defaults: { _controller: VisuConsultationBundle:Cartographie:InfobullePC }
    requirements:
        echelle: (maille(100|200|500|1|2|5|10|_utm_10))|communes|precise
        maille_id: ([A-Z0-9]+)
    options:
        expose: true

visu_carto_richesse_taxo_geojson:
    path:     /indicateur/richesseTaxonomique.geojson
    defaults: { _controller: VisuConsultationBundle:Cartographie:geoJsonRichesseTaxo }
    options:
        expose: true

visu_carto_richesse_taxo_infobulle:
    path:     /information/richesseTaxonomique/{echelle}/{maille_id}
    defaults: { _controller: VisuConsultationBundle:Cartographie:InfobulleRichesseTaxo }
    requirements:
        echelle: (maille(100|200|500|1|2|5|10|_utm_10))|communes|precise
        maille_id: ([A-Z0-9]+)
    options:
        expose: true

visu_carto_taxon_repartition_geojson:
    path: /cartographie/repartition-taxon/{cd_ref}.geojson
    defaults: { _controller: VisuConsultationBundle:Cartographie:repartitionTaxon }
    requirements:
        cd_ref:   \d+
    options:
        expose: true

visu_carto_taxon_repartition_infobulle:
    path:     /information/repartition-taxon/{cd_ref}/{echelle}/{maille_id}
    defaults: { _controller: VisuConsultationBundle:Cartographie:InfobulleRepartitionTaxon }
    requirements:
        cd_ref: \d+
        echelle: (maille(100|200|500|1|2|5|10|_utm_10))|communes|precise
        maille_id: ([A-Z0-9]+)
    options:
        expose: true


visu_consultation_commune_autocomplete:
    path:     /commune/recherche/{commune}
    defaults: { _controller: VisuConsultationBundle:Commune:autocomplete, _format:json }
    options:
        expose: true



visu_carto_territoire_geojson:
    path:     /cartographie/territoires.geojson
    defaults: { _controller: VisuConsultationBundle:Cartographie:geoJsonTerritoire, _format:json }
    options:
        expose: true
