api_biblio_publication:
    resource: "@APIBiblioBundle/Controller/PublicationController.php"
    type:     rest
    prefix: /

api_biblio_auteur:
    resource: "@APIBiblioBundle/Controller/AuteurController.php"
    type:     rest
    prefix: /

api_biblio_auteur_type:
    resource: "@APIBiblioBundle/Controller/AuteurTypeController.php"
    type:     rest
    prefix: /

api_biblio_listes:
    resource: "@APIBiblioBundle/Controller/ListesController.php"
    type:     rest
    prefix: /


api_biblio_form:
    resource: "@APIBiblioBundle/Resources/config/routes/form.routing.yml"
    prefix:   /form
    type: rest

#api_biblio_publication:
#    resource: "@APIBiblioBundle/Resources/config/routes/publication.routing.yml"
#    prefix:   /
#    type: rest



api_biblio_territoire_all:
    path:     /territoire
    defaults: { _controller: APIBiblioBundle:Territoire:getAll }

api_biblio_localisation_all:
    path:     /localisation
    defaults: { _controller: APIBiblioBundle:Localisation:getAll }

api_biblio_rangement_cat1_all:
    path:     /rangement/cat1
    defaults: { _controller: APIBiblioBundle:Rangement:getAllCat1 }

api_biblio_taxon_all:
    path:     /taxon
    defaults: { _controller: APIBiblioBundle:Taxon:getAll }

api_biblio_guilde_all:
    path:     /guilde
    defaults: { _controller: APIBiblioBundle:Guilde:getAll }