services:
    api.listener.authentication_success_response:
        class: API\CoreBundle\EventListener\AuthenticationSuccessListener
        arguments: [%jwt_token_ttl%]
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }
    api.listener.jwt_expired_listener:
        class: API\CoreBundle\EventListener\JWTExpiredListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_expired, method: onJWTExpired }
    api.listener.jwt_not_found_listener:
        class: API\CoreBundle\EventListener\JWTInvalidListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_not_found, method: onJWTNotFound }
    api.listener.jwt_invalid_listener:
        class: API\CoreBundle\EventListener\JWTInvalidListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_invalid, method: onJWTInvalid }
    api.listener.authentication_failure_listener:
        class: API\CoreBundle\EventListener\AuthenticationFailureListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_failure, method: onAuthenticationFailureResponse }
    api_core_uuid:
        class: API\CoreBundle\Services\UUID