api_biblio_publication_recherche:
    path:     /publication/recherche
    defaults: { _controller: APIBiblioBundle:Publication:searchPublication }
    methods:    [POST]

api_biblio_publication_get_all:
    path:     /publication
    defaults: { _controller: APIBiblioBundle:Publication:getPublication }
    methods:    [GET]

api_biblio_publication_create:
    path:     /publication
    defaults: { _controller: APIBiblioBundle:Publication:savePublication }
    methods:    [POST]