parameters:
    communes:
        geom:
            id: insee_comm
            table: referentiel.communes_fr
            the_geom: the_geom
        data:
            id: id_unique
            table: referentiel.indicateur_communes
            total: nb_obs
    maille10:
        geom:
            id: code10km
            table: referentiel.grille_maille_10km
            the_geom: the_geom
        data:
            id: id_unique
            table: referentiel.indicateur_maille10
            total: nb_obs
    maille5:
        geom:
            id: code5km
            table: referentiel.grille_maille_5km
            the_geom: the_geom
        data:
            id: id_unique
            table: referentiel.indicateur_maille5
            total: nb_obs
    maille2:
        geom:
            id: code_maille
            table: referentiel.grille_maille_2km
            the_geom: the_geom
        data:
            id: id_unique
            table: referentiel.indicateur_maille2
            total: nb_obs
    maille1:
        geom:
            id: code_maille
            table: referentiel.grille_maille_1km
            the_geom: the_geom
        data:
            id: id_unique
            table: referentiel.indicateur_maille1
            total: nb_obs
    maille500:
        geom:
            id: code_maille
            table: referentiel.grille_maille_500m
            the_geom: the_geom
        data:
            id: id_unique
            table: referentiel.indicateur_maille500
            total: nb_obs
    maille200:
        geom:
            id: code_maille
            table: referentiel.grille_maille_200m
            the_geom: the_geom
        data:
            id: id_unique
            table: referentiel.indicateur_maille200
            total: nb_obs
    maille100:
        geom:
            id: code_maille
            table: referentiel.grille_maille_100m
            the_geom: the_geom
        data:
            id: id_unique
            table: referentiel.indicateur_maille100
            total: nb_obs
    precise:
        geom:
            id: id_unique
            table: referentiel.pointage_precis
            the_geom: the_geom
        data:
            id: id_unique
            table: referentiel.indicateur_precis
            total: nb_obs