services:
    api_carto.service.layer:
        # as no class is configured, the parent service MUST be abstract
        abstract:  true
        arguments: ["@doctrine.dbal.serena_db_connection", "@security.authorization_checker", "@security.token_storage", "@router", "@request_stack"]

    api_carto.service.indicateur:
        # as no class is configured, the parent service MUST be abstract
        abstract:  true
        parent: api_carto.service.layer

    api_carto.service.pression_connaissance:
        class: API\CartoBundle\Services\Cartographie\PressionConnaissanceService
        parent: api_carto.service.indicateur
        tags:
            - { name: service.pression_connaissance, alias: api_carto_service_pression_connaissance }

    api_carto.service.richesse_taxonomique:
        class: API\CartoBundle\Services\Cartographie\RichesseTaxonomiqueService
        parent: api_carto.service.indicateur
        tags:
            - { name: service.richesse_taxonomique, alias: api_carto_service_richesse_taxonomique }

    api_carto.service.repartition_taxonomique:
        class: API\CartoBundle\Services\Cartographie\RepartitionTaxonomiqueService
        parent: api_carto.service.layer
        tags:
            - { name: service.repartition_taxonomique, alias: api_carto_service_repartition_taxonomique }


parameters:
    nb_taxon_par_page: 30