parameters:
    communes:
        geom:
            id: insee_comm
            table: referentiel.communes_fr
            the_geom: the_geom
        data:
            id: id_unique
            table: referentiel.indicateur_communes
            total: nb_obs
    maille10:
        geom:
            id: code10km
            table: referentiel.grille_maille_10km
            the_geom: the_geom
        data:
            id: id_unique
            table: referentiel.indicateur_maille10
            total: nb_obs
    maille5:
        geom:
            id: code5km
            table: referentiel.grille_maille_5km
            the_geom: the_geom
        data:
            id: id_unique
            table: referentiel.indicateur_maille5
            total: nb_obs
    maille2:
        geom:
            id: code_maille
            table: referentiel.grille_maille_2km
            the_geom: the_geom
        data:
            id: id_unique
            table: referentiel.indicateur_maille2
            total: nb_obs
    maille1:
        geom:
            id: code_maille
            table: referentiel.grille_maille_1km
            the_geom: the_geom
        data:
            id: id_unique
            table: referentiel.indicateur_maille1
            total: nb_obs
    maille500:
        geom:
            id: code_maille
            table: referentiel.grille_maille_500m
            the_geom: the_geom
        data:
            id: id_unique
            table: referentiel.indicateur_maille500
            total: nb_obs
    maille200:
        geom:
            id: code_maille
            table: referentiel.grille_maille_200m
            the_geom: the_geom
        data:
            id: id_unique
            table: referentiel.indicateur_maille200
            total: nb_obs
    maille100:
        geom:
            id: code_maille
            table: referentiel.grille_maille_100m
            the_geom: the_geom
        data:
            id: id_unique
            table: referentiel.indicateur_maille100
            total: nb_obs
    precise:
        geom:
            id: id_unique
            table: referentiel.pointage_precis
            the_geom: the_geom
        data:
            id: id_unique
            table: referentiel.indicateur_precis
            total: nb_obs



    communes_hab:
        geom:
            id: insee_comm
            table: referentiel.communes_fr
            the_geom: the_geom
        data:
            id: id_unique
            table: referentiel.indicateur_hab_communes
            total: nb_obs
    maille10_hab:
        geom:
            id: code10km
            table: referentiel.grille_maille_10km
            the_geom: the_geom
        data:
            id: id_unique
            table: referentiel.indicateur_hab_maille10
            total: nb_obs
    maille5_hab:
        geom:
            id: code5km
            table: referentiel.grille_maille_5km
            the_geom: the_geom
        data:
            id: id_unique
            table: referentiel.indicateur_hab_maille5
            total: nb_obs
    maille2_hab:
        geom:
            id: code_maille
            table: referentiel.grille_maille_2km
            the_geom: the_geom
        data:
            id: id_unique
            table: referentiel.indicateur_hab_maille2
            total: nb_obs
    maille1_hab:
        geom:
            id: code_maille
            table: referentiel.grille_maille_1km
            the_geom: the_geom
        data:
            id: id_unique
            table: referentiel.indicateur_hab_maille1
            total: nb_obs
    maille500_hab:
        geom:
            id: code_maille
            table: referentiel.grille_maille_500m
            the_geom: the_geom
        data:
            id: id_unique
            table: referentiel.indicateur_hab_maille500
            total: nb_obs
    maille200_hab:
        geom:
            id: code_maille
            table: referentiel.grille_maille_200m
            the_geom: the_geom
        data:
            id: id_unique
            table: referentiel.indicateur_hab_maille200
            total: nb_obs
    maille100_hab:
        geom:
            id: code_maille
            table: referentiel.grille_maille_100m
            the_geom: the_geom
        data:
            id: id_unique
            table: referentiel.indicateur_hab_maille100
            total: nb_obs




    communes_suivi:
        geom:
            id: insee_comm
            table: referentiel.communes_fr
            the_geom: the_geom
        data:
            id: gid
            table: spatial_data.suivis
            suivi: suivi
    maille10_suivi:
        geom:
            id: code10km
            table:  referentiel.grille_maille_10km
            the_geom: the_geom
        data:
            id: gid
            table: spatial_data.suivis
            suivi: suivi
    maille5_suivi:
        geom:
            id: code5km
            table: referentiel.grille_maille_5km
            the_geom: the_geom
        data:
            id: gid
            table: spatial_data.suivis
            suivi: suivi
    maille2_suivi:
        geom:
            id: code_maille
            table: referentiel.grille_maille_2km
            the_geom: the_geom
        data:
            id: gid
            table: spatial_data.suivis
            suivi: suivi
    maille1_suivi:
        geom:
            id: code_maille
            table:  referentiel.grille_maille_1km
            the_geom: the_geom
        data:
            id: gid
            table: spatial_data.suivis
            suivi: suivi
    maille500_suivi:
        geom:
            id: code_maille
            table: referentiel.grille_maille_500m
            the_geom: the_geom
        data:
            id: gid
            table: spatial_data.suivis
            suivi: suivi
    maille200_suivi:
        geom:
            id: code_maille
            table: referentiel.grille_maille_200m
            the_geom: the_geom
        data:
            id: gid
            table: spatial_data.suivis
            suivi: suivi
    maille100_suivi:
        geom:
            id: code_maille
            table: referentiel.grille_maille_100m
            the_geom: the_geom
        data:
            id: gid
            table: spatial_data.suivis
            suivi: suivi