services:
#    ofsa_consultation.service.consultvalid:
#        # as no class is configured, the parent service MUST be abstract
#        abstract:  true
#        arguments: [@doctrine.orm.ofsa_entity_manager, @security.context, @form.factory, @request_stack, @core_tools.service.verificateur_data]
#
#    ofsa_consultation.service.consultation:
#        class: OFSA\ConsultationBundle\Services\ConsultationService
#        parent: ofsa_consultation.service.consultvalid
#        arguments: [@router]
#        tags:
#            - { name: service.consultation, alias: ofsa_consultation_service_consultation }
#
#    ofsa_consultation.service.validation:
#        class: OFSA\ConsultationBundle\Services\ValidationService
#        parent: ofsa_consultation.service.consultvalid
#        tags:
#            - { name: service.validation, alias: ofsa_consultation_service_validation }
#
#
#
    visu_consultation.service.layer:
        # as no class is configured, the parent service MUST be abstract
        abstract:  true
        arguments: ["@doctrine.dbal.serena_db_connection", "@security.authorization_checker", "@security.token_storage", "@router", "@request_stack"]

    visu_consultation.service.indicateur:
        # as no class is configured, the parent service MUST be abstract
        abstract:  true
        parent: visu_consultation.service.layer

    visu_consultation.service.pression_connaissance:
        class: Visu\ConsultationBundle\Services\Cartographie\PressionConnaissanceService
        parent: visu_consultation.service.indicateur
        tags:
            - { name: service.pression_connaissance, alias: visu_consultation_service_pression_connaissance }

    visu_consultation.service.richesse_taxonomique:
        class: Visu\ConsultationBundle\Services\Cartographie\RichesseTaxonomiqueService
        parent: visu_consultation.service.indicateur
        tags:
            - { name: service.richesse_taxonomique, alias: visu_consultation_service_richesse_taxonomique }

    visu_consultation.service.repartition_taxonomique:
        class: Visu\ConsultationBundle\Services\Cartographie\RepartitionTaxonomiqueService
        parent: visu_consultation.service.layer
        tags:
            - { name: service.repartition_taxonomique, alias: visu_consultation_service_repartition_taxonomique }

    visu_taxon.service.taxref:
        class: Visu\ConsultationBundle\Services\TaxrefService
        arguments: ["@doctrine.orm.mc_taxref_db_entity_manager"]
        tags:
            - { name: service.taxref, alias: visu_taxon_service_taxref }

    twig.extension.json_decode:
        class: Visu\ConsultationBundle\Twig\Extension\JsonDecodeExtension
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }

    visu_consultation.service.spatial:
        class: Visu\ConsultationBundle\Services\SpatialService
        arguments: ["@doctrine.dbal.serena_db_connection", "@security.authorization_checker", "@security.token_storage"]
        tags:
            - { name: service.spatial, alias: visu_consultation_service_spatial }


parameters:
    nb_taxon_par_page: 30